language: node_js
node_js:
  - 6
  - 8
  - 10
env:
  - FLUTURE_VERSION=^7.1.2
  - FLUTURE_VERSION=^8.0.0
  - FLUTURE_VERSION=^9.0.0
  - FLUTURE_VERSION=^10.0.0
before_script: npm i fluture@$FLUTURE_VERSION
